import type { Module } from "../types/module";

export const modules: Module[] = [
  {
    id: 1,
    title: "Simples Nacional",
    section: "Automação",
    status: "ativo",
    description: "Gerencia obrigações do Simples Nacional.",
    image: "./simplesnacional.svg",
  },
  {
    id: 2,
    title: "Hub Alertas +",
    section: "Automação",
    status: "ativo",
    description: "Gerencia obrigações do Hub Alertas +.",
    image: "./hubalertas3.svg",
  },
  {
    id: 3,
    title: "DCTF Automatizada",
    section: "Automação",
    status: "manutencao",
    description: "Gerencia obrigações do DCTF Automatizada.",
    image: "./dtfautomatizada.svg",
  },
  {
    id: 4,
    title: "Calculo de Imposto Retido",
    section: "Automação",
    status: "ativo",
    description: "Realiza o calculo do imposto retido.",
    image: "./calcimposto.png",
  },
  {
    id: 5,
    title: "Central CND",
    section: "Automação",
    status: "ativo",
    description: "Gerencia obrigações do CND.",
    image: "./centralcnd.svg",
  },
  {
    id: 6,
    title: "Mensagem do Governo",
    section: "Automação",
    status: "manutencao",
    description: "Caixa de entrada para as mensagens do governo.",
    image: "./hubalertas2.svg",
  },
  {
    id: 7,
    title: "Consulta Simei",
    section: "Automação",
    status: "ativo",
    description: "Realiza a consulta do SIMEI.",
    image: "./consultaimpostos.svg",
  },
  {
    id: 8,
    title: "Impostos Pagos",
    section: "Automação",
    status: "manutencao",
    description: "Calculo de Impostos Pagos.",
    image: "./consultaimpostos.svg",
  },
  {
    id: 9,
    title: "HubCount BI",
    section: "Relatórios",
    status: "manutencao",
    description: "Dashboard BI da sua empresa.",
    image: "../hubcountbi.svg",
    classe: "hubcount-bi",
  },
  {
    id: 10,
    title: "BI da Folha",
    section: "Relatórios",
    status: "ativo",
    description: "Dashboard BI da Folha.",
    image: "./bidafolha.svg",
    classe: "bidafolha",
  },
  {
    id: 11,
    title: "HubConcilia",
    section: "Relatórios",
    status: "ativo",
    description: "Gerencia obrigações do Hub Concilia.",
    image: "./hubconcilia.png",
    classe: "hubconcilia",
  },
  {
    id: 12,
    title: "Lalur",
    section: "Relatórios",
    status: "ativo",
    description: "Gerencia obrigações do Lalur.",
    image: "./lalur.png",
    classe: "lalur",
  },
  {
    id: 13,
    title: "Report Contábil",
    section: "Relatórios",
    status: "ativo",
    description: "Gerencia obrigações do Report Contábil.",

  },
];
